<div class="large-5 columns">
          <div class="panel logopanel">
            <a href="/homes/claytonnorris/"><img class="logo" src="/homes/img/expressions_logo.png" alt="Expressions"></a>
          </div>
          <div class="panel logopanelsub">
            <p>Expressions by Decor & More, Inc. was founded in 1986 and is a leading supplier to the home building, manufactured housing and recreational vehicle industries. The Expressions facilities, in Millersburg, In are filled with over 31,000 square feet of the most unique and affordable home decor merchandise. Our interior designs and home decor have been featured at International Building Shows and received the Excellence in Home Design Award for Outstanding Model Merchandiser.</p>
          </div>
		  <div>
		  	<ul class="vcard">
			  <li class="phone">574-642-3577</li>
			  <li class="street-address">101 Maple Street</li>
			  <li><span class="city">Millersburg</span>, <span class="state">IN</span> <span class="zip">46543</span></li>
			  <li class="email"><a href="mailto:info@expressionsdecor.com">info@expressionsdecor.com</a></li>
			</ul>
		  </div>
      </div>